import type { Metadata } from 'next';
import { Open_Sans } from 'next/font/google';
import './globals.css';
import NavItems from '@/components/NavItems';
import '@code-hike/mdx/dist/index.css';
const sans = Open_Sans({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={sans.className}>
        <header className="mt-5 px-24 flex justify-between">
          <p className="text-2xl font-bold">Pooreum's Blog</p>
          <NavItems />
        </header>
        <div className="p-24">{children}</div>
      </body>
    </html>
  );
}
